
on: [push]
  
jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run days
        run: |
          for d in `ls -1`; do
            if [[ -e $d/app.py ]]; then
              pushd $d
              python app.py
              popd
            fi
          done
